name: image_capture_test
description: Test capture image
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image_picker: ^0.8.4+2
  path_provider: ^2.0.1
  http: ^0.13.0
  gallery_saver: ^2.3.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/camera_icon.png"

flutter:
  uses-material-design: true
